### ISSUE TITLE
Adding alert points causes crash

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#1]
Steps:
1. Hamburger menu
2. Add Alert
3. Add an Alert
4. Publish it
5. Go back to map
6. Reload app
7. Tap the added point

Results:
Crash (nothing happens; uncaught exception)

Notes:
If trying to reload the app on a link that will take you to an alert popover, the app fails to load and the map is just a grey box.

Config:
Safari 9.1.3 on Mac

**Comment by samfalconer** [comment]
Did debugging and verification in Safari on Mac

**Comment by asmasattar** [comment]
Hey Sam, give some comments as to what your fix does. Once you add comments it looks good to ship. Good job!

**Comment by samfalconer** [comment]
Merged to master.
