### ISSUE TITLE
Determine minimum browsers and show an alert if the user is under the minimum

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#100]
For the web version we should determine minimum browsers and show an alert if the user is under the minimum.

**Comment by Wally-Werner** [comment]
Does this need some testing to determine what the minimum level of browsers is, or do we just need to declare that the current level of browsers are the minimum, and then test for that level and display a message if the user is running less than the minimum?  I'd vote to use the current level of browser version as the minimum - I don't see a need to make it work with older browsers.

**Comment by jsieber-aca** [comment]
We decided to go with the current level. I forget the exact feature set that is required, but we decided to prompt users to update their browser if they don't meet the required level. Hope that makes sense.

**Comment by Wally-Werner** [comment]
Totally. That’s what I was trying to say.  (-:

 

Thanks!

**Comment by samfalconer** [comment]
Pushing now to make the build. Holding open for review.

**Comment by samfalconer** [comment]
Working reliably, but checks and displays error if applicable on every page load.

Closing out this one, but filing #138 to see if we can just have it display on the initial app load.
