### ISSUE TITLE
Initial map view should be zoomed to Continental US if location can't be found

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#101]
The current initial zoom level is showing almost the entire world. Once many services and alert points are created this will overload the map with points. The initial zoom should only show a few miles around the current device location.

**Comment by samfalconer** [comment]
I believe you should only see the whole world if it can't find your location. I see the few miles around behavior when it does find me.

Should we maybe change the zoom and position if it doesn't find you to be the Continental United States instead of the Earth?

**Comment by jsieber-aca** [comment]
I agree, this is working on my mobile device, but not in the web view through a standard browser. 

Is the web browser version attempting to find the current location? I'm not getting a dialog allowing me to allow or disallow my browser from using my location and it is opening the world view. 

I'm thinking that we will probably want to zoom in even tighter than the United States.

**Comment by jsieber-aca** [comment]
I just noticed that when I run this in my local environment, the initial view is zoomed in to my location. When I run the current production web view, this does not happen. I verified that my browser, Google Chrome,  is allowing the site to determine my location. Not sure why I'm seeing different behavior between the two envirnoments.

**Comment by jsieber-aca** [comment]
@Wally-Werner Can you check and see if this works on your phone. It works on my phone and my local environment, but I get the entire world on the production web view. I have Chrome set to allow my location to be discovered, so I'm not sure why it won't work in only the production web view.

**Comment by samfalconer** [comment]
I think this is just because the web view has a bigger viewport. It's still centered on the US for me. Closing.
