### ISSUE TITLE
Tapping Services does nothing

### ISSUE THREAD

**Issue by Jeremy-Friedman** [Tour-de-Force/btc-app#108]
Steps:
1) Create a service
2) Click/tap it 

Results:
1) Nothing happens

Expected:
1) Point menu appears

Verified on:
1) Chrome 53.0.2785.143
2) Android 6.0.1

**Comment by samfalconer** [comment]
Can we get some console output for this? If this is reproducible this could be high priority.

**Comment by Jeremy-Friedman** [comment]
I misreported this. Turns out I forgot to re-link btc-models before verifying.
