### ISSUE TITLE
UI Inconsistency Between Services/Alerts

### ISSUE THREAD

**Issue by Jeremy-Friedman** [Tour-de-Force/btc-app#109]
Steps:
1) Create a service. Notice the "Next" button is gray until the user enters a name and type.
2) Create an alert. Notice the "Submit" button is blue, but does nothing until the user enters a name and type.

Expected: 
1) "Submit" button should be gray until name/type fields have been entered when creating an alert.

Verified on:
Chrome 53.0.2785.143
Android 6.0.1

**Comment by samfalconer** [comment]
Duplicate of https://github.com/Tour-de-Force/btc-app/issues/81 ?

**Comment by Jeremy-Friedman** [comment]
Ah, I suppose so! Closing.
