### ISSUE TITLE
"Show Track" button doesn't do anything

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#11]
Steps:
1. Go to "Download Track" page
2. Click "Show Track" on USBR 20

Results:
Nothing happens

**Comment by jsieber-aca** [comment]
Actually, if you return to the map using the menu, the track is displayed. The formatting of this screen has issues, as the "Save" and "Show Track" buttons are almost completely hidden on my device.

**Comment by samfalconer** [comment]
Ohhhh, okay.

I think I tried that but must have run into https://github.com/Tour-de-Force/btc-app/issues/3

The cutoff problem is being tracked by https://github.com/Tour-de-Force/btc-app/issues/9

**Comment by samfalconer** [comment]
Austin, I think we can close this one.

**Comment by amk5401** [comment]
Confirmed that #3 and #9 are making it look like this is a bug when in fact it is not.
