### ISSUE TITLE
install fails on ios-deploy dependency

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#110]
On my Windows environment, the install fails due to the ios-deploy dependency.

**Comment by jsieber-aca** [comment]
Added pull request https://github.com/Tour-de-Force/btc-app/pull/111 to resolve this issue.

**Comment by samfalconer** [comment]
This changes a dev dependency to a production dependency, but I've been wanting to move all the dependencies required for build to production anyway.

To;dr: Ship it!
