### ISSUE TITLE
Website input in a service forces validation for uri when empty if focus is taken

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#114]
When creating a new service if you type any character in the Website input and then remove it, you are unable to move forward as the validation fails. This is also a problem if you edit and existing service and attempt to remove an existing URL. 

The wesite url validation should only execute if the input is not an empty string. 

We also may want to update the validation message as the average user may not be familiar with what the "uri format" is.

**Comment by samfalconer** [comment]
Looks and tests great! Ship it!

**Comment by samfalconer** [comment]
Merged. Closing.
