### ISSUE TITLE
Register and Login pages have different password requirements

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#12]
Steps:
1. Register with a very short password (I believe 4 characters will work)
2. Be successful registering
3. Try to login with that password

Results:
You are told the password is too short even though you were allowed to register with it.

**Comment by samfalconer** [comment]
It looks like the minimum is 8 chars to me.

I would check out btc-models user.js line 123 and below. It seems like that part is not being properly used for registration, but the login one below it is being used for login.

**Comment by samfalconer** [comment]
Also fixing the problem in models should make sure it validates server side as well.

**Comment by Jeremy-Friedman** [comment]
This ended up being a model issue. See: https://github.com/Tour-de-Force/btc-models/issues/12
