### ISSUE TITLE
Password reset email link responding with 404

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#120]
When I try to follow the link in the password reset email I receive I'm getting a 404 with the following response. 

Cannot GET /reset-password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpzaWViZXJAYWR2ZW50dXJlY3ljbGluZy5vcmciLCJyb2xlcyI6W10sImlhdCI6MTQ3OTIyNjg4NiwiZXhwIjoxNDc5MjI4MDg2LCJpc3MiOiJiaWN5Y2xldG91cmluZ2NvbXBhbmlvbi5jb20ifQ.TtSbSiQDhPvmeIpAb33SE329eyYrXgAuIWdBvuZXW_k

**Comment by samfalconer** [comment]
@amk5401 Looks like the link is pointing to the API server and not to the web client server.

**Comment by amk5401** [comment]
https://github.com/Tour-de-Force/btc-app-server/pull/39

**Comment by samfalconer** [comment]
Fixed by fixing server issue. Closing.
