### ISSUE TITLE
Onboarding panels

### ISSUE THREAD

**Issue by Wally-Werner** [Tour-de-Force/btc-app#128]
Add the ability to show a set of onboarding panels when the app is launched the first time. Plan for up to 5 onboarding panels (panel 1: welcome, panel 2: how the map works, panel 3: contribute by adding points, panel 4: contribute by adding comments & flags, panel 5: enjoy your bike tour

**Comment by amk5401** [comment]
I will look into these panels being simple html/page that can be updated easily by sponsor without having to comb through code.

**Comment by samfalconer** [comment]
Looks and tests great! Ship it!

**Comment by amk5401** [comment]
merged
