### ISSUE TITLE
Onboarding panels available through settings

### ISSUE THREAD

**Issue by Wally-Werner** [Tour-de-Force/btc-app#129]
Add a new button/link on the settings page that allow the user to see the onboarding panels again.

**Comment by amk5401** [comment]
![screenshot_20170212-122600](https://cloud.githubusercontent.com/assets/6664199/22864414/f48d66b0-f11e-11e6-9e2b-abb4ede832e5.png)

**Comment by samfalconer** [comment]
Merged. Closing.
