### ISSUE TITLE
Publish page doesn't show feedback upon successful or unsuccessful publish

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#13]
Steps:
1. Add a POI or Alert
2. Go to publish page
3. Click Publish (while online or off)

Results:
In either case (online or off) there is no feedback other than the list clearing if online and publish succeeded

**Comment by samfalconer** [comment]
The error (offline) case was handled by: https://github.com/Tour-de-Force/btc-app/issues/30

**Comment by samfalconer** [comment]
Merging now to make the build cutoff. Leaving open for final review.

**Comment by asmasattar** [comment]
Tested out, also looked at the code. Works great! Ship 🛳it!

**Comment by samfalconer** [comment]
Reviewed; closing (already pushed).
