### ISSUE TITLE
Make login optional to start; mandatory for adding services/comments

### ISSUE THREAD

**Issue by Wally-Werner** [Tour-de-Force/btc-app#130]
Do the following to the login process:
1) Once logged in, persist the login/session for a long time, something like 3 months.
2) When the app starts for the first time, do not force a login in order to begin viewing maps, services and comments.
3) When the user decides to contribute a service, comment or alert, then go to the login screen.

**Comment by samfalconer** [comment]
Merged to make the build. Leaving open for review.

**Comment by amk5401** [comment]
flag is gone for alerts - switch if statement  for LoggedIn and if point==service

**Comment by samfalconer** [comment]
Merged to make the build. Leaving open for review.

**Comment by samfalconer** [comment]
Closing as this is complete and it is the end of the year.
