### ISSUE TITLE
Enhance the publishing process for points/comments

### ISSUE THREAD

**Issue by Wally-Werner** [Tour-de-Force/btc-app#132]
Do the following:
1) If logged in, auto-publish points/comments as they are entered.
2) If not logged in, save points in the drawer (as it currently works)
3) Upon login or re-connection of the app to the internet, auto-publish any points saved in the drawer.
4) At the conclusion of the publish process, if online, display an informational message as a timed alert at the top of the page that says "Service Published" or "Comment Published".
5) At the conclusion of the publish process, if offline, display an informational message as a timed alert at the top of the page that says "Offline; Info Saved for Later".

**Comment by samfalconer** [comment]
Merging to make the build. Leaving open for review.

**Comment by samfalconer** [comment]
Ship it (with one comment to be fixed in master)

**Comment by samfalconer** [comment]
Merged. Closing.
