### ISSUE TITLE
Data Loss: Updating a service a second time before publishing saves first edits

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#149]
Steps:

1. Edit a service
2. Save edits (don't publish)
3. Edit again
4. Publish

Results:
First set of edits are saved

Expected:
Last set of edits be saved

**Comment by jsieber-aca** [comment]
Thanks for finding this, definitely high priority.

**Comment by samfalconer** [comment]
The redux store isn't getting the new _rev from Pouch after it's generated, and it causing a silent Pouch document update conflict error, which is cool.

**Comment by samfalconer** [comment]
Merging now to make the build. Leaving open for review.

**Comment by amk5401** [comment]
ship it

**Comment by samfalconer** [comment]
Approved. Closing.
