### ISSUE TITLE
Frequent replication failures in production

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#150]
Steps:

1. Open app in production

Results:
Replication failure and no points

**Comment by jsieber-aca** [comment]
I tried this from the web view and on the first try, it seemed to replicate. After resetting the app again and also using the Clear Point Cache option it will no longer replicate the existing points.

**Comment by jsieber-aca** [comment]
@samfalconer - not sure if you just fixed this, but I was now just able to replicate the points.

**Comment by samfalconer** [comment]
Yeah, I think it might be WebKit specific for a storage limit or something. Either way it's very slow. Also, I think it was sometimes failing for me with WebKit before we loaded down the production DB with photos.

Definitely needs investigation before nailing down a fix.

**Comment by jsieber-aca** [comment]
I forgot about the photo issue, that could be part of it for sure. It does seem to be a little random.

**Comment by samfalconer** [comment]
Just for the record, I'm rebooting AWS couch right now to test a thing related to this.

**Comment by jsieber-aca** [comment]
Sounds good.

**Comment by samfalconer** [comment]
So the config change in Couch didn't help, but I do have a thing that seems to work around the occasional random connection drops during (usually initial) replication in Safari.

Also the big images were definitely the slowness part, and I will take care of them on the image issue.

**Comment by samfalconer** [comment]
Approved by Austin in the PR. Merged. Closing.
