### ISSUE TITLE
Sync-on-demand services before editing

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#152]
If a user is online, when the go to edit a service we should sync that point to make sure they have up to date info.

This won't solve merge conflicts, but will help from the user experince persepective.

**Comment by jsieber-aca** [comment]
Merge conflicts will still result when other users have saved point data offline, but otherwise, it should keep from overwriting data that may have been updated after the last point replication, correct. Just wanting to make sure we are on the same page with this.

**Comment by samfalconer** [comment]
Yes, that's my understanding too.

**Comment by jsieber-aca** [comment]
Thanks for verifying!

**Comment by amk5401** [comment]
pull request #174

**Comment by samfalconer** [comment]
Looks great! Ship it like an ocean liner! 🚢

**Comment by jsieber-aca** [comment]
This appears to be fixed. Closing.
