### ISSUE TITLE
Expiration date on Alerts

### ISSUE THREAD

**Issue by asmasattar** [Tour-de-Force/btc-app#155]
Add an optional expiration date to Alert points. If it is selected show the expiration date on the Alert point. If it is not selected let the user know there is no expiration date selected. Once the time has passed beyond that Alert point _expire the alert point_ . This means do not show point on map. Point expiration date can be removed and changed in CouchDB.

**Comment by samfalconer** [comment]
Looks and tests great! Ship it!

**Comment by asmasattar** [comment]
Merged.
