### ISSUE TITLE
~20sec load time for no apparent reason

### ISSUE THREAD

**Issue by amk5401** [Tour-de-Force/btc-app#16]
Environment: Htc m8 Android version 6.0

Steps:
1. Cold start app on phone

Results:
The time to load is anywhere from 5-25 seconds. Using Chrome remote debugger to look at resource load times seems like the code is not taking a long time to run, however loading the javascript files seems to take up the time.

**Comment by Jeremy-Friedman** [comment]
Verified on my Android 6.0.1

**Comment by jsieber-aca** [comment]
I believe this might be resolved once the images are separated from the other data that is being replicated.

**Comment by jsieber-aca** [comment]
I think this is resolved. Will allow you to close once verified.

**Comment by samfalconer** [comment]
iOS cold start speeds have been much better recently. We will check Android.

**Comment by Jeremy-Friedman** [comment]
Consistently takes 5 - 6 seconds on my Android 7.0. Ship it

**Comment by samfalconer** [comment]
Closing.
