### ISSUE TITLE
iOS - touches are sticking and when a new page loads

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#160]
IOS - touches are sticking and when a new page loads that click transfers to another clickable
options. [ ex: clicked on hamburger —> clicked on settings —> (as it loads the settings pages
the click transfers to… ) —> Clear points cache (and clears the points) ]. This means that
anything in the publish drawer will get removed.
Another example is if you login. Logging in adds the username to the settings page. When you
go to the settings page the button that the previous click you did will stick to the “Reset app”
button. The entire app is than reset! It clears everything and kicks you back to the panels.

**Comment by samfalconer** [comment]
Merging to make the build. Leaving open for review.

**Comment by asmasattar** [comment]
Howdy! You broke onboarding 😬

**Comment by samfalconer** [comment]
#173 isn't a terrible workaround that breaks everything.

It might even be the right fix!

**Comment by samfalconer** [comment]
Merging to make the build. Leaving open for review.

**Comment by samfalconer** [comment]
Merging (most recent PR) to make the build. Leaving open for review.

**Comment by amk5401** [comment]
ship/sheep it

**Comment by samfalconer** [comment]
Merged. Closing.
