### ISSUE TITLE
Hamburger Menu - Flex box needs to be fixed.

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#161]
Hamburger menu - flex box need to be fixed. The menu disappears when you
go into Settings, Download track page, Filter, Publish, About page, Logout page, and you do
anything to resize the window. I know the menu bar is still there but the color that makes you be
able to see it is removed on resize. Everything collides as you expand and shrink the window.
It’s not using the same format as the “map”, “add service” and “add alert page”.

**Comment by samfalconer** [comment]
Merged to make the build. Leaving open for review.

**Comment by jsieber-aca** [comment]
This seems to be working for me in the web view.

**Comment by asmasattar** [comment]
Looks good! Ship!

**Comment by samfalconer** [comment]
Merged. Closing.
