### ISSUE TITLE
We *need* HTTPS

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#164]
We are communicating sensitive data to Couch and the Server in plain text. We need HTTPS for these.

**Comment by jsieber-aca** [comment]
Agreed, high priority. Thanks for remembering this.

**Comment by samfalconer** [comment]
This locks down the communication between the clients and the load balancers.

We still need to lock down communication between the load balancers and the servers backing them. I'm tracking that issue here: https://github.com/Tour-de-Force/btc-infrastructure/issues/6

**Comment by samfalconer** [comment]
Merging to make the build. Leaving open for review.

**Comment by amk5401** [comment]
sheep it

**Comment by samfalconer** [comment]
Merged. Closing.
