### ISSUE TITLE
Some registration messages persist that shouldn't

### ISSUE THREAD

**Issue by Jeremy-Friedman** [Tour-de-Force/btc-app#176]
Steps:
1) Attempt to login with an invalid email and/or pw OR attempt to register with an already registered email
2) Exit registration UI from step 1, return to it

Expected:
The "Your email or password are incorrect." or "Document update conflict" (browser) / "There is already an account with that email address." (Android) notification goes away.

Actual:
Aforementioned notification persists.

**Comment by samfalconer** [comment]
Just took care of this while investigating users being logged out.

**Comment by samfalconer** [comment]
Merging to make build. Leaving open for review.

**Comment by amk5401** [comment]
ship

**Comment by samfalconer** [comment]
Merged. Closing.
