### ISSUE TITLE
We should explicitly set minimum OSes

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#18]
Right now, we don't explicitly set minimum versions of Android or iOS.
They happen to be iOS 8.0 and Android 4.0 (API 14).

This is causing us all kinds of problems when newer Javascript things are used that aren't polyfilled on older OSes.

We should explicitly set minimum OSes. I suggest iOS 8.0 and Android 4.4 (API 19).

Android 4.4 was released Fall 2013.
iOS 8.0 was released Fall 2014.

Android 4.4 was the first version that supported Chrome Remote Debugging, so I don't think we should go any lower, or it will be a pain to debug.

These are fairly generous ranges for these OSes, and should allow us to focus our debugging efforts.

**Comment by Jeremy-Friedman** [comment]
I agree - the number of users I expect to have issues with us supporting 2.5 - 3.5 year old OS's (assuming a May '17 release) isn't significant enough to outweigh hindered development (ie, until we identify a better tool than Chrome Remote Debugging that can go farther back than 4.4). Let's run it by John on Tuesday.

**Comment by samfalconer** [comment]
Putting this into this weeks build. Will revert if John disagrees.

**Comment by samfalconer** [comment]
Merged
