### ISSUE TITLE
Point card should allow user to see comments and reviews without them having to go into the UI for leaving a comment or review.

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#181]
It is difficult to find the existing comments and reviews. We should have a way to see them on the point card without going into the menu and selecting the option to "Rate Service".

**Comment by jsieber-aca** [comment]
Increasing priority to high. This is an important feature of the app and many users will not find ratings or reviews in its current location.

**Comment by samfalconer** [comment]
Merged. Approved by Jeremy in PR. Closing.
