### ISSUE TITLE
Filter icons on map screen?

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#184]
It appears that both buttons/icons on the map view are for filtering the service points? What was the intention of the two buttons again? Seems like we only need one for filtering.

**Comment by jsieber-aca** [comment]
I now remember that the top button shows a listing of services/alerts in the area. When I click this, it shows a list and then moves automatically to the first item in the list. This is confusing behavior.

**Comment by jsieber-aca** [comment]
The filter button also is opening the filter select input automatically. The desktop version does not do this.

**Comment by jsieber-aca** [comment]
How does this top button determine what data to show and how to sort it. If I'm viewing the map in Michigan, but select this text view, the top item is an alert in Montana.

**Comment by samfalconer** [comment]
Unfortunately, the list view lists every point in the world. (Probably not sorted any specific way)

**Comment by samfalconer** [comment]
Opening the filter select automatically should be fixed in build 15

**Comment by jsieber-aca** [comment]
I'm going to close this issue and make a new issue that is more specific to the list functionality. The list functionality still needs some work.
