### ISSUE TITLE
Don't open popover (Camera/Library) if you are in a browser. Only open if on phone

### ISSUE THREAD

**Issue by asmasattar** [Tour-de-Force/btc-app#202]

**Comment by Jeremy-Friedman** [comment]
Unable to get to this part of the UI at the moment when trying to trying to update an existing service. Otherwise, works when creating a new service on Android/browser. Aforementioned issue happens on master as well, so I'm assuming it's an unrelated to this PR. Therefore: ship it.

**Comment by samfalconer** [comment]
Merged. Closing.

**Comment by jsieber-aca** [comment]
This appears to be working correctly for me in the browser version.
