### ISSUE TITLE
If user leaves a review without being logged in, a dialog flashes stating that you need to login to publish points.

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#208]
I left a comment while not logged in and I get a dialog along the bottom stating, "You must be logged in to publish points".

This will be an issue if the user is offline and has not current connection.

**Comment by samfalconer** [comment]
As discussed in the meeting, this was due to a combination of an old session and timing fixes that will be addressed in the review for #132
