### ISSUE TITLE
"Forgot password?" button does nothing

### ISSUE THREAD

**Issue by Jeremy-Friedman** [Tour-de-Force/btc-app#22]
Steps:
1. Tap hamburger menu
2. Tap "Login"
3. Tap "Forgot password?"

Results:
Nothing happens

Expected Results:
Ask user for their email. Once provided, email them a password reset link. Or something to that effect.

**Comment by samfalconer** [comment]
This is higher priority now based on sponsor meeting.

**Comment by amk5401** [comment]
I'm taking a look at this

**Comment by samfalconer** [comment]
All yours

Be sure to note that we might need a web ui / front end server unless there is a more clever way to do the reset flow than emailing a link to a web form.

**Comment by samfalconer** [comment]
Fantastic! One nitpick, but doesn't need re-review. Can you change the URLs themselves (and all links to them) to look more like the existing ones ie: "/forgotPassword" becomes "forgot-password" and so on. The names of the classes are fine as-is, but I think it makes sense to stay consistent here.

Once that's changed go forth and ship it! 🛳

**Comment by samfalconer** [comment]
Also, if you could open separate issues on the other repos if you need to make PRs there in the future that would be really helpful for my build bookkeeping.

(Also [also] don't forget to update the link in the email with the new URL format.)

**Comment by samfalconer** [comment]
Merged. Closing.
