### ISSUE TITLE
App doesn't work on iOS 8

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#23]
Steps:
1. Open app on iOS 8.1 iPhone 5s simulator

Results:
Attached screenshot

<img width="432" alt="screen shot 2016-09-26 at 5 06 25 pm" src="https://cloud.githubusercontent.com/assets/3956038/18851835/c200438c-840b-11e6-8325-58158c10d5b4.png">

**Comment by samfalconer** [comment]
It's slightly better on iOS 8.4, but the Add Service page was missing the tab bar.

**Comment by samfalconer** [comment]
Approved to bump version requirement to iOS 9.0

**Comment by asmasattar** [comment]
I didn't test it but it makes complete sense. Looked at code and everything seems right to me. Ship 🛳 it!

**Comment by samfalconer** [comment]
Merged.
