### ISSUE TITLE
Account creation - Document Update conflict

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#24]
If a user tries to create an account with an email address that is already associated with an existng account the following error will occur, "Document update conflict". A better error message would be useful here. 

I ran into this bug after creating an account that had a password that is too short. That bug is already logged.

**Comment by samfalconer** [comment]
Related to https://github.com/Tour-de-Force/btc-app/issues/52

Apparently this error does display.

**Comment by samfalconer** [comment]
Moving to server: https://github.com/Tour-de-Force/btc-app-server/issues/22
