### ISSUE TITLE
Cordova-Plugin-Whitelist doesn't support iOS

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#25]
Cordova-Plugin-Whitelist doesn't support iOS. We should figure out what to do about that.

**Comment by samfalconer** [comment]
I think if we update our stuff per #42 we should be good here.

**Comment by jsieber-aca** [comment]
Can this be closed now that the dependencies have been updated?

**Comment by samfalconer** [comment]
Yes, it looks like iOS has the functionality natively in the iOS platform support: https://taco.visualstudio.com/en-us/docs/cordova-security-whitlists/#cordova-whitelists
