### ISSUE TITLE
Service ratings are not unique to the entity

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#29]
When I create a new service it shows existing ratings that appear to be hard coded into the app. A new service should not have any existing ratings and new rating for that service should persist to only that service.

**Comment by samfalconer** [comment]
This looks like the smokiest of the mirrors (all fake).

See rating-point-card.js for hardcoded mockComments array. I see nothing about ratings in btc-models either. This is bordering on feature work.

**Comment by samfalconer** [comment]
There actually is some work for the model layer for a "Comment" at the bottom of point.js in btc-models.

**Comment by samfalconer** [comment]
Also, we should probably make the comment field and star rating clear on successful comment, but I can't figure out how to do that right now.

**Comment by samfalconer** [comment]
IMPORTANT: Test this with Tour-de-Force/btc-models#21

**Comment by samfalconer** [comment]
Pushing now to make the build. Holding open for review.

**Comment by asmasattar** [comment]
This all looks good, and it's working well.

**Comment by samfalconer** [comment]
Already merged. Closing.
