### ISSUE TITLE
Buttons randomly don't work on the first or second click

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#3]
Steps:
1. Open POI popover
2. Click "Close" button

Results:
**Sometimes** clicking the button shows the click animation, but does nothing.

Notes:
This seems to happen randomly with **any button** in the app.

Config:
Safari 9.1.3 on Mac

**Comment by samfalconer** [comment]
iOS seems to suffer from this problem too. Must be a WebKit thing.

**Comment by samfalconer** [comment]
Did initial merge, but we'll need to come back and actually review this.

**Comment by asmasattar** [comment]
I tested it and it works great! Ship 🛳 it!

**Comment by samfalconer** [comment]
Been merged, but now closing.
