### ISSUE TITLE
If you don't publish services you no longer have option on next opening of app.

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#30]
I created two new services in the app. They showed in the publishing menu, but when I close and reopen the map, I no longer have the option to publish the new services. They show on my map, so must exist in my local storage. If I don't publish the new services, they should remain in my publishing drawer until I publish them or delete them from local storage.

**Comment by samfalconer** [comment]
Austin checked this locally and it worked as expected.

**Comment by samfalconer** [comment]
Merged.
