### ISSUE TITLE
Use of OpenCycleMap as base layer

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#36]
If we use OpenCycleMap as the base layer we will be able to display multiple USBRS routes that already exist in the data as well as other regional cycling routes. http://www.opencyclemap.org/about/

Downsides of this are that it makes it difficult to find existing routes without zooming around the map. Upside is that routes will be added automatically as they are added to the OpenCycleMap data layer.

**Comment by samfalconer** [comment]
Great work! Ship it! 🛳

**Comment by asmasattar** [comment]
Merged
