### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#42]
While building/installing a lot of our dependencies complain about being deprecated. We should update (at least) the ones that are complaining.

**Comment by samfalconer** [comment]
Here is the patch: https://github.com/Tour-de-Force/btc-app/commit/0cb09fdf76e2acc16bcea80b2e35b0fa3cea379a

I wanted to get this into master soon anyway so we can find issues, and git was being a pain.

**Comment by amk5401** [comment]
ship

**Comment by samfalconer** [comment]
Merged. Closing.
