### ISSUE TITLE
Server errors encountered during registration aren't displayed

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#52]
Steps:
1. Be pointed at a local server that isn't running (like being offline)
2. Try to register (submit the form)

Results:
No user feedback, but there is console spew about something being passed in the wrong format

**Comment by Jeremy-Friedman** [comment]
Ship it (although you might want to change "Unable to connect to server" to "Unable to connect to the server."

**Comment by samfalconer** [comment]
Updated string and merged.
