### ISSUE TITLE
Points of interest should be associated with users who added/edited them

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#53]
Right now the DB doesn't keep track of who is adding/editing POIs. We should keep track of that.

**Comment by samfalconer** [comment]
This is somewhat related to #14

**Comment by asmasattar** [comment]
I moved this enhancement to btc-app-models & btc-app-server. Links below.

https://github.com/Tour-de-Force/btc-app-server/issues/29
https://github.com/Tour-de-Force/btc-models/issues/13
