### ISSUE TITLE
Publish count wrong after updating service info

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#54]
Steps:
1. Add a POI
2. Edit some info and save
3. Open hamburger menu

Results:
Publish count is 2 when only one point shows in publish view

**Comment by samfalconer** [comment]
The local storage list has 2 keys pointing at the same place.

**Comment by samfalconer** [comment]
Merging now to make the build cutoff. Leaving open for final review.

**Comment by asmasattar** [comment]
Tested it, also looked at the code. Thanks for adding comments. Works great! ship 🛳 it!

**Comment by samfalconer** [comment]
Reviewed; closing (already pushed).
