### ISSUE TITLE
unable to edit service name

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#55]
From @jsieber-aca -
This is on iOS, will need to validate that it is happening on Android.
I created a new service but accidentally misspelled the name. If I try to update the service, I'm only able to update Phone Number, Address, etc. not the actual service name. I could delete and start over again but should not have to.

**Comment by samfalconer** [comment]
Happening in Chrome desktop as well.

Looks like we need the tab with the pencil on it added to the editing wizard.

**Comment by samfalconer** [comment]
IMPORTANT: This needs to be tested and pushed with https://github.com/Tour-de-Force/btc-models/issues/10

**Comment by Jeremy-Friedman** [comment]
Ship it.

**Comment by samfalconer** [comment]
Merged.
