### ISSUE TITLE
Update service screen allows the selection of tabs but does not change screen.

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#56]
From @jsieber-aca -
While trying to update a service on iOS, I'm able to move from tab to tab but the content of the screen remains on the Description page. Clicking on the hours or amenity tab highlights the tab but does not change the screen.

**Comment by samfalconer** [comment]
Happening in Chrome desktop as well.

Possibly related to the dependency upgrade.

**Comment by Jeremy-Friedman** [comment]
Ship it!

**Comment by samfalconer** [comment]
Merged.
