### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by asmasattar** [Tour-de-Force/btc-app#6]
User is unable to login. Getting 400 bad request on "Login" button click. I get the same 400 bad request error from other button actions on the app, like on the "sign up" button.

**Comment by samfalconer** [comment]
This was an issue on Asma's computer. The CouchDB admin wasn't setup.

This fixes the different length problem: https://github.com/Tour-de-Force/btc-app/issues/12

**Comment by samfalconer** [comment]
Closing (Duplicate/Config Issue)
