### ISSUE TITLE
Attempting to publish after deleting cache greys UI and makes it static

### ISSUE THREAD

**Issue by Jeremy-Friedman** [Tour-de-Force/btc-app#60]
Create a POI. 
Delete the POI (delete cache via settings)
Go to Hamburger Menu.
Click on Publish (1) 

Results: can't navigate anyhwere via the Hamburger Menu without UI greying out/becoming static. Publish button still has "(1)" denotation for the POI that was supposedly deleted as well. 

Identified on Chrome version 53.0.2785.143

**Comment by samfalconer** [comment]
It sounds like you're wiping out your browsers local databases (where the points are kept), but not the local storage (where the updated point list is kept). There might also be some session state hanging around without refreshing.

Is this a use case we should worry about? Could this lead to other bugs?

**Comment by Jeremy-Friedman** [comment]
Source of problem: uncaught TypeError in src/js/components/point-list.js line 24. Attempt being made to access point var's coverUrl field, but point is undefined.

**Comment by samfalconer** [comment]
I misunderstood this problem. The "delete cache" button in the app itself is the source of the problem.

**Comment by samfalconer** [comment]
Fixed by fixing #85. Closing.
