### ISSUE TITLE
When you click the close button on a service detail OpenStreetMap opens

### ISSUE THREAD

**Issue by dbarth-aca** [Tour-de-Force/btc-app#66]
![click](https://cloud.githubusercontent.com/assets/6394248/19495743/ecf823a6-9541-11e6-8824-500c0c70463f.jpg)
When you click the close button on a service it opens up the OpenStreetMap link that is found on the bottom of the map (behind the button). That then takes you to the copyright and License page.

**Comment by samfalconer** [comment]
Breaks the app; high.

**Comment by samfalconer** [comment]
I've started looking at this.

**Comment by samfalconer** [comment]
Let's talk about moving these links to an "About" page or something in the meeting.

**Comment by asmasattar** [comment]
looks like it's working well  - ship 🛳 it!

**Comment by samfalconer** [comment]
Merged.
