### ISSUE TITLE
Show version number in about screen of app.

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#67]
It would be very helpful to see the current version number in the app itself. I would think in the settings screen. When I look at my Android application manager it just lists version 1.0 instead of the actual version 1.05. This is nice enhancement for those reporting issues.

**Comment by samfalconer** [comment]
I'm adding an About page for https://github.com/Tour-de-Force/btc-app/issues/66

I'll do this then.

**Comment by asmasattar** [comment]
Looked at the code and tested it. looks good to me - ship 🛳 it!

**Comment by samfalconer** [comment]
Merged.
