### ISSUE TITLE
Some service points have a large pointer image and hide information

### ISSUE THREAD

**Issue by dbarth-aca** [Tour-de-Force/btc-app#68]
![service1toobig](https://cloud.githubusercontent.com/assets/6394248/19496039/f8e4f33c-9542-11e6-9ad1-9941d4bb815f.jpg)
![service2](https://cloud.githubusercontent.com/assets/6394248/19496043/fe99c154-9542-11e6-90fc-81deaaf27998.jpg)
Some services have a large pointer image and some of the text gets cut off. Also the menu button is also obstructed. Some look fine and you can access the menu fine.

**Comment by samfalconer** [comment]
Work blocking; promoting to high.

**Comment by asmasattar** [comment]
I tested it both on Safari & Firefox and it runs great! Ship 🛳it!

**Comment by samfalconer** [comment]
Merged.
