### ISSUE TITLE
When hours are not inputted for a service it displays as closed.

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#69]
Hours are not required when creating a service. If they are left blank, the service displays, "Not Open Today". If there are no hours entered at all, it would be better to not show anything or a message that hours have not been added. 

Showing that the service is closed could be misleading. This might require changes to the filtering by open services option as well.

**Comment by samfalconer** [comment]
Per meeting; this is high.

**Comment by samfalconer** [comment]
NOTE: This must be tested with https://github.com/Tour-de-Force/btc-models/issues/15

**Comment by asmasattar** [comment]
Tested it and it runs great. However, was thinking maybe the dash after "Hours not available" should not be there when there aren't any hours specified. but other than that you can ship 🛳it b/c the initial issue is completed.

**Comment by samfalconer** [comment]
Merged.
