### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by asmasattar** [Tour-de-Force/btc-app#7]
Registration may be associated with the Login issue (https://github.com/Tour-de-Force/btc-app/issues/6) . It gives the same 400 bad request error.

**Comment by samfalconer** [comment]
This was an issue on Asma's computer. The CouchDB admin wasn't setup.

This fixes the different length problem: #12

**Comment by samfalconer** [comment]
Closing (Duplicate/Config Issue)
