### ISSUE TITLE
Add alert validation errors don't display

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#81]
1. Add an alert, but don't set the type
2. Try to save it

Results: Validation fails, so the alert doesn't save, but the error only prints to the console.

**Comment by samfalconer** [comment]
Looks great! Ship it!

**Comment by asmasattar** [comment]
Merged!

**Comment by jsieber-aca** [comment]
On my Android device the validation shows as soon as the tab is shown, instead of showing if the form is submitted without the values like the web app works. Might not be worth fixing, but thought I would mention the difference in behavior.
