### ISSUE TITLE
Refreshing the app logs you out

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#85]
1. Login
2. Click refresh in your browser

Results: You are now logged out.

**Comment by samfalconer** [comment]
We should investigate saving all the state locally (including login state). We currently only do this (manually) with the updated points list.

Maybe there's a more general way to do this,

**Comment by samfalconer** [comment]
This along with all the Redux stuff clearing on refresh is annoying. We should fix this so we don't have to keep logging in when developing.

**Comment by samfalconer** [comment]
See here: https://github.com/rt2zz/redux-persist

**Comment by asmasattar** [comment]
Lots of files! great work cleaning this all up. Seems to be working well.

**Comment by samfalconer** [comment]
Merged. Closing.
