### ISSUE TITLE
Track cards are cutoff if screen is too short

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#9]
Steps:
1. Have a short enough screen
2. Go to "Download Track" page

Results:
Some parts of cards (including buttons) can be cut off

![screen shot 2016-09-14 at 3 20 59 pm](https://cloud.githubusercontent.com/assets/3956038/18526695/8ba79ff4-7a8f-11e6-94e7-7373c05e9191.png)

**Comment by amk5401** [comment]
Should be fixed in pull request #31 

- Needs to be verified however

**Comment by samfalconer** [comment]
Looks great! I tested in responsive design mode and works well.

Ship it!

**Comment by amk5401** [comment]
Closing. Fixed in merge commit af8ce33521fad6bd1282dee0362f06d3dbe36319
