### ISSUE TITLE
Photo upload is not functional

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#91]
When creating a service or alert, the option to upload a photo does not do anything. I'm guessing that this was just a facade by the team last year. 

Steps to replicate:
1. Create a new service.
2. On the Add Details screen use Upload Photo link.
3. Select a photo from device photo gallery.
4. After selecting a photo from the device gallery the user is returned to the Add Details screen. No photo is uploaded or saved.

**Comment by samfalconer** [comment]
The way we're doing it now, the browser is blocked on https://issues.apache.org/jira/browse/CB-9852

You can actually click the "Upload Photo" button and scroll down to use the file upload button as a workaround in the browser. This worked for me all the way through getting the photo to the server.

We could special case the browser.

I also tested on iOS and the upload worked for me.

Was it possible that the photo was added, but there was just no user feedback?
Maybe check if the photo is added once you complete the wizard. Try going to that POI and see if the photo is attached.

**Comment by jsieber-aca** [comment]
I was able to test on Android and iOS today. The feature does work on iOS but does not work on my Android device. I was able to upload a photo from the web view once I realized where the file upload button is placed in the bottom left-hand corner. 

I think we have three separate issues that I will create and then close this existing issue.

**Comment by jsieber-aca** [comment]
After several tries I was finally able to upload an image from my Android device. I'm wondering if it seems like it does not work as photos from the phone camera are high resolution and slow to upload?
