### ISSUE TITLE
Ability to take photo from App

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#92]
In relation to issue 91, https://github.com/Tour-de-Force/btc-app/issues/91, it would be nice to be able to take a photo with the device camera directly within the app. Currently, the user only has the option to select an existing image from the device gallery. This requires the user to have taken the photo in advance or edit the existing service/alert after the initial creation.

**Comment by samfalconer** [comment]
Merging to make the build. Leaving open for review.

**Comment by Jeremy-Friedman** [comment]
Ship it

**Comment by samfalconer** [comment]
Merged. Closing.
