### ISSUE TITLE
When running as a desktop app, "Upload Photo" does not do anything

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#93]
When using the desktop version of the app the "Upload Photo" feature does not do anything. On the mobile apps, this button launches the device's photo gallery and allows the user to select an image file. On the desktop version, it would be nice if the button was able to open a file manager so that the user could select an image file saved on the file system.

**Comment by amk5401** [comment]
It does do something, however it is hard to notice. The page gets longer and if you scroll down, the 'Choose File' button is visible, and clicking this opens the file manager that you were looking for. Obviously this is not ideal, but it does do something.

![image](https://cloud.githubusercontent.com/assets/6664199/21162782/287b1cc0-c15d-11e6-87bc-0437f35ebd83.png)

**Comment by jsieber-aca** [comment]
I'm not sure that each click on the upload photo button should open an additional "Choose File" input if the previous input has not yet been used to select an image.

**Comment by samfalconer** [comment]
Merged to make the build. Leaving open for review.

**Comment by samfalconer** [comment]
Closing as this is complete and it is the end of the year.
