### ISSUE TITLE
Button to bring user to current location on map

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#94]
If the user has allowed access to their devices location there should be a button that will allow the user to zoom to their current location. The crosshairs icon is typically used for this. I could see this feature to be located on the upper left or right corner of the map.

**Comment by jsieber-aca** [comment]
Raising priority on this based on additional user feedback.

**Comment by samfalconer** [comment]
Merged. Approved by Jeremy in the PR. Closing.
