### ISSUE TITLE
Different point types should have different pins on the map

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-app#97]
There is currently no way to tell what a pin is by looking at it on the map.

Services and Alerts should at least look different from each other.

The next step would be to make each kind of thing: "camping", "bike shop", "flooding" have unique pins.

**Comment by samfalconer** [comment]
This is bothering everyone and seems low hanging. I'll try to fit it in soon.

**Comment by jsieber-aca** [comment]
I forgot to bring this one up in the meeting but would be a good one to tackle if time permits. These could even just be color coded if we provide a legend to explain the colors.

**Comment by samfalconer** [comment]
Looks great! Ship it!
